// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: servicio.proto

package Grupo10_Laboratorio_3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiMensaje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
}

func (x *MiMensaje) Reset() {
	*x = MiMensaje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiMensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiMensaje) ProtoMessage() {}

func (x *MiMensaje) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiMensaje.ProtoReflect.Descriptor instead.
func (*MiMensaje) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{0}
}

func (x *MiMensaje) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_servicio_proto protoreflect.FileDescriptor

var file_servicio_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2a, 0x0a, 0x09, 0x4d, 0x69, 0x4d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x3a, 0x0a, 0x0a, 0x4d, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x69, 0x6f, 0x12, 0x2c, 0x0a, 0x08, 0x4d, 0x69, 0x4d, 0x65, 0x74, 0x6f, 0x64, 0x6f, 0x12,
	0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x69, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x73, 0x2d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x69, 0x64, 0x6f, 0x73, 0x2d, 0x32, 0x30, 0x32, 0x33, 0x2d, 0x30, 0x32, 0x2f, 0x47, 0x72,
	0x75, 0x70, 0x6f, 0x31, 0x30, 0x2d, 0x4c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x69,
	0x6f, 0x2d, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servicio_proto_rawDescOnce sync.Once
	file_servicio_proto_rawDescData = file_servicio_proto_rawDesc
)

func file_servicio_proto_rawDescGZIP() []byte {
	file_servicio_proto_rawDescOnce.Do(func() {
		file_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(file_servicio_proto_rawDescData)
	})
	return file_servicio_proto_rawDescData
}

var file_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_servicio_proto_goTypes = []interface{}{
	(*MiMensaje)(nil), // 0: main.MiMensaje
	(*Respuesta)(nil), // 1: main.Respuesta
}
var file_servicio_proto_depIdxs = []int32{
	0, // 0: main.MiServicio.MiMetodo:input_type -> main.MiMensaje
	1, // 1: main.MiServicio.MiMetodo:output_type -> main.Respuesta
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_servicio_proto_init() }
func file_servicio_proto_init() {
	if File_servicio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servicio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiMensaje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servicio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicio_proto_goTypes,
		DependencyIndexes: file_servicio_proto_depIdxs,
		MessageInfos:      file_servicio_proto_msgTypes,
	}.Build()
	File_servicio_proto = out.File
	file_servicio_proto_rawDesc = nil
	file_servicio_proto_goTypes = nil
	file_servicio_proto_depIdxs = nil
}
