// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: servicio.proto

package Grupo10_Laboratorio_3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgregarBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreSector string  `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string  `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	Valor        float32 `protobuf:"fixed32,3,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *AgregarBaseRequest) Reset() {
	*x = AgregarBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgregarBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgregarBaseRequest) ProtoMessage() {}

func (x *AgregarBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgregarBaseRequest.ProtoReflect.Descriptor instead.
func (*AgregarBaseRequest) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{0}
}

func (x *AgregarBaseRequest) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *AgregarBaseRequest) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

func (x *AgregarBaseRequest) GetValor() float32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type RenombrarBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreSector string `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	NuevoNombre  string `protobuf:"bytes,3,opt,name=nuevo_nombre,json=nuevoNombre,proto3" json:"nuevo_nombre,omitempty"`
}

func (x *RenombrarBaseRequest) Reset() {
	*x = RenombrarBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenombrarBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenombrarBaseRequest) ProtoMessage() {}

func (x *RenombrarBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenombrarBaseRequest.ProtoReflect.Descriptor instead.
func (*RenombrarBaseRequest) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *RenombrarBaseRequest) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *RenombrarBaseRequest) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

func (x *RenombrarBaseRequest) GetNuevoNombre() string {
	if x != nil {
		return x.NuevoNombre
	}
	return ""
}

type ActualizarValorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreSector string  `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string  `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	NuevoValor   float32 `protobuf:"fixed32,3,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"`
}

func (x *ActualizarValorRequest) Reset() {
	*x = ActualizarValorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualizarValorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarValorRequest) ProtoMessage() {}

func (x *ActualizarValorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarValorRequest.ProtoReflect.Descriptor instead.
func (*ActualizarValorRequest) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{2}
}

func (x *ActualizarValorRequest) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *ActualizarValorRequest) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

func (x *ActualizarValorRequest) GetNuevoValor() float32 {
	if x != nil {
		return x.NuevoValor
	}
	return 0
}

type BorrarBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreSector string `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
}

func (x *BorrarBaseRequest) Reset() {
	*x = BorrarBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrarBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrarBaseRequest) ProtoMessage() {}

func (x *BorrarBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrarBaseRequest.ProtoReflect.Descriptor instead.
func (*BorrarBaseRequest) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{3}
}

func (x *BorrarBaseRequest) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *BorrarBaseRequest) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Exitoso bool   `protobuf:"varint,2,opt,name=exitoso,proto3" json:"exitoso,omitempty"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{4}
}

func (x *Respuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *Respuesta) GetExitoso() bool {
	if x != nil {
		return x.Exitoso
	}
	return false
}

type GetSoldadosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreSector string `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
}

func (x *GetSoldadosRequest) Reset() {
	*x = GetSoldadosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSoldadosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoldadosRequest) ProtoMessage() {}

func (x *GetSoldadosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoldadosRequest.ProtoReflect.Descriptor instead.
func (*GetSoldadosRequest) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{5}
}

func (x *GetSoldadosRequest) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *GetSoldadosRequest) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

type RegistroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lineas []string `protobuf:"bytes,1,rep,name=lineas,proto3" json:"lineas,omitempty"`
}

func (x *RegistroRequest) Reset() {
	*x = RegistroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroRequest) ProtoMessage() {}

func (x *RegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroRequest.ProtoReflect.Descriptor instead.
func (*RegistroRequest) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{6}
}

func (x *RegistroRequest) GetLineas() []string {
	if x != nil {
		return x.Lineas
	}
	return nil
}

type RegistroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lineas  []string `protobuf:"bytes,1,rep,name=lineas,proto3" json:"lineas,omitempty"`
	Exitoso bool     `protobuf:"varint,2,opt,name=exitoso,proto3" json:"exitoso,omitempty"`
}

func (x *RegistroResponse) Reset() {
	*x = RegistroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroResponse) ProtoMessage() {}

func (x *RegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroResponse.ProtoReflect.Descriptor instead.
func (*RegistroResponse) Descriptor() ([]byte, []int) {
	return file_servicio_proto_rawDescGZIP(), []int{7}
}

func (x *RegistroResponse) GetLineas() []string {
	if x != nil {
		return x.Lineas
	}
	return nil
}

func (x *RegistroResponse) GetExitoso() bool {
	if x != nil {
		return x.Exitoso
	}
	return false
}

var File_servicio_proto protoreflect.FileDescriptor

var file_servicio_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x70, 0x0a, 0x12, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x7f, 0x0a, 0x14, 0x52, 0x65, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x75,
	0x65, 0x76, 0x6f, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x7f, 0x0a, 0x16, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x73, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x65,
	0x76, 0x6f, 0x5f, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x6e, 0x75, 0x65, 0x76, 0x6f, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x59, 0x0a, 0x11, 0x42, 0x6f,
	0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x42, 0x61, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x69, 0x74, 0x6f, 0x73, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x78, 0x69, 0x74, 0x6f, 0x73, 0x6f, 0x22, 0x5a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c,
	0x64, 0x61, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x73, 0x22, 0x44, 0x0a,
	0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x69,
	0x74, 0x6f, 0x73, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x78, 0x69, 0x74,
	0x6f, 0x73, 0x6f, 0x32, 0xfb, 0x02, 0x0a, 0x0a, 0x4d, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x69, 0x6f, 0x12, 0x38, 0x0a, 0x0b, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73,
	0x65, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x3c, 0x0a, 0x0d,
	0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x40, 0x0a, 0x0f, 0x41, 0x63,
	0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x1c, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56,
	0x61, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x0a,
	0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x61,
	0x64, 0x6f, 0x73, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f,
	0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x41,
	0x0a, 0x10, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x6f, 0x73, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x73, 0x2d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x69, 0x64, 0x6f, 0x73, 0x2d, 0x32, 0x30, 0x32, 0x33, 0x2d, 0x30, 0x32, 0x2f, 0x47, 0x72,
	0x75, 0x70, 0x6f, 0x31, 0x30, 0x2d, 0x4c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x69,
	0x6f, 0x2d, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servicio_proto_rawDescOnce sync.Once
	file_servicio_proto_rawDescData = file_servicio_proto_rawDesc
)

func file_servicio_proto_rawDescGZIP() []byte {
	file_servicio_proto_rawDescOnce.Do(func() {
		file_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(file_servicio_proto_rawDescData)
	})
	return file_servicio_proto_rawDescData
}

var file_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_servicio_proto_goTypes = []interface{}{
	(*AgregarBaseRequest)(nil),     // 0: main.AgregarBaseRequest
	(*RenombrarBaseRequest)(nil),   // 1: main.RenombrarBaseRequest
	(*ActualizarValorRequest)(nil), // 2: main.ActualizarValorRequest
	(*BorrarBaseRequest)(nil),      // 3: main.BorrarBaseRequest
	(*Respuesta)(nil),              // 4: main.Respuesta
	(*GetSoldadosRequest)(nil),     // 5: main.GetSoldadosRequest
	(*RegistroRequest)(nil),        // 6: main.RegistroRequest
	(*RegistroResponse)(nil),       // 7: main.RegistroResponse
}
var file_servicio_proto_depIdxs = []int32{
	0, // 0: main.MiServicio.AgregarBase:input_type -> main.AgregarBaseRequest
	1, // 1: main.MiServicio.RenombrarBase:input_type -> main.RenombrarBaseRequest
	2, // 2: main.MiServicio.ActualizarValor:input_type -> main.ActualizarValorRequest
	3, // 3: main.MiServicio.BorrarBase:input_type -> main.BorrarBaseRequest
	5, // 4: main.MiServicio.GetSoldados:input_type -> main.GetSoldadosRequest
	6, // 5: main.MiServicio.ObtenerRegistros:input_type -> main.RegistroRequest
	4, // 6: main.MiServicio.AgregarBase:output_type -> main.Respuesta
	4, // 7: main.MiServicio.RenombrarBase:output_type -> main.Respuesta
	4, // 8: main.MiServicio.ActualizarValor:output_type -> main.Respuesta
	4, // 9: main.MiServicio.BorrarBase:output_type -> main.Respuesta
	4, // 10: main.MiServicio.GetSoldados:output_type -> main.Respuesta
	7, // 11: main.MiServicio.ObtenerRegistros:output_type -> main.RegistroResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_servicio_proto_init() }
func file_servicio_proto_init() {
	if File_servicio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servicio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgregarBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenombrarBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualizarValorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrarBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSoldadosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicio_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servicio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicio_proto_goTypes,
		DependencyIndexes: file_servicio_proto_depIdxs,
		MessageInfos:      file_servicio_proto_msgTypes,
	}.Build()
	File_servicio_proto = out.File
	file_servicio_proto_rawDesc = nil
	file_servicio_proto_goTypes = nil
	file_servicio_proto_depIdxs = nil
}
